language: bash

matrix:
  include:
    - os: linux
      dist: focal
      script: bash linux_installer.sh

    - os: windows
      script: powershell -ExecutionPolicy ByPass -File windows_installer.ps1
