name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  beautify:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run beautysh
        uses: illvart/beautysh-action@latest
        with:
          # Pass beautysh options in args:
          args: "*.sh --indent-size 4"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[auto] CI: apply beautysh formatting."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
