name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-20.04", "windows-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install (Linux)
        run: bash linux_installer.sh
        if: matrix.os == 'ubuntu-20.04'

      - name: Install (Windows)
        run: powershell -ExecutionPolicy ByPass -File windows_installer.ps1
        if: matrix.os == 'windows-latest'
